on:   
  push:
    branches:
      - main
name: variable substitution in json

jobs:
  build:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v2
      - uses: microsoft/variable-substitution@v1 
        with: 
          files: 'OnlinePortfolioZB/OnlinePortfolioZB/appsettings.json'
      env:
          EmailSettings.SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}
          EmailSettings.Sender_Name: ${{secrets.from_email_name}}
          EmailSettings.From_Email: ${{secrets.from_email}}
